### PR TITLE
Viewer/Editor Fixes for #825 and #824

### PR DESCRIPTION
**Pull request by pskowronek**
Fixes for:
- #825 - fixed NPE
- #824 - commented out the change - need to find a better way to default to utf-8

### CODE REVIEW

**Review by ahadas — COMMENTED** [review]
@pskowronek  functionality wise, it was good but I've posted another commit to replace the method with FileterInputSream and replaced the AtomicBoolean with an array, what do you think?

**Comment by pskowronek** [comment]
> @pskowronek functionality wise, it was good but I've posted another commit to replace the method with FileterInputSream and replaced the AtomicBoolean with an array, what do you think?

I saw it :)
- `FileterInputSream` - good
- `AtomicBoolean` -> array - a matter of taste I would say (I prefer `AtomicBoolean` way)
- inline override FileterInputSream directly inside `startEditing` method - again a matter of taste (I like doing that via additional method to have cleaner code)

But overall, it is OK

**Review by pskowronek — COMMENTED** [review]
I've commented in the conversation.
BTW, I cannot approve as I github forbids me to approve 'my own PR' :)

**Comment by ahadas** [comment]
> I've commented in the conversation. BTW, I cannot approve as github forbids me to approve 'my own PR' :)

that's ok :)
and I've replaced the boolean array with AtomicBoolean, I wasn't sure if I like that as well..

**Pull request merged**
