### PR TITLE
Get a default shell for current user under macOS #728

### PR DESCRIPTION
**Pull request by pskowronek**
PR for https://github.com/mucommander/mucommander/issues/728

### CODE REVIEW

**Comment by ahadas** [comment]
@pskowronek I tried the posted change and it didn't remove the deprecation warning for me - the configured shell I got from `dscl . -read ~/ UserShell` was /bin/bash and so nothing really changed. I posted another PR that sets the environment variable BASH_SILENCE_DEPRECATION_WARNING to silent that warning but I like the direction of this PR nevertheless - how about trying to use DesktopAdapter#getDefaultShell so if the user configures a custom shell we'll take it?

**Comment by pskowronek** [comment]
Regarding the warning - if you have /bin/bash by default, and no BASH_SILENCE_DEPRECATION_WARNING=1 in profile then you shouldn't see the warning. If you open Terminal then you have this warning or not? I wouldn't set BASH_SILENCE_DEPRECATION_WARNING explicitly in muC, tho. The terminal should start as if it was started by Terminal app etc.

I saw DesktopAdapter#getDefaultShell and it is more for command execution and not for interactive shell.

I was wondering if shell shouldn't be configurable (via preferences), to let user set the shell to their liking.

**Comment by ahadas** [comment]
> Regarding the warning - if you have /bin/bash by default, and BASH_SILENCE_DEPRECATION_WARNING=1 in profile then you shouldn't see the warning. If you open Terminal then you have this warning or not?

yes, I see that warning when opening the terminal since I didn't set the env var BASH_SILENCE_DEPRECATION_WARNING

> I wouldn't set BASH_SILENCE_DEPRECATION_WARNING explicitly in muC, tho. The terminal should start as if it was started by Terminal app etc.

generally, I'd agree - but in the long term I would like us to replace the separate terminal window with a widget. I remember seeing it with previous file managers I used in the past - in my opinion it's a better user experience then switching between the windows, and then I wouldn't want to have those three lines that take space

> I saw DesktopAdapter#getDefaultShell and it is more for command execution and not for interactive shell.

yes, it's used by the run-command dialog which I hope to replace with jediterm and later, to drop that dialog when we have that integrated widget

> I was wondering if shell shouldn't be configurable (via preferences), to let user set the shell to their liking.

+1
and with the changes described above we can have a single configuration for the shell that will be used in both the terminal window and run-command dialog

**Comment by ahadas** [comment]
On a second thought, it could have been better to clear the screen completely when initiating the terminal..

**Comment by pskowronek** [comment]
> @pskowronek, how about polishing #733? is there something else you work on for v1.1.0?

@ahadas  - so, what's the decision? What should be done here for v1.1.0?

**Comment by ahadas** [comment]
@pskowronek how about:
1. retrieve the default as you do here (the one that appears in Preferences -> Misc -> Run command
2. use that, or the custom shell that the user configures there, for jediterm

**Comment by pskowronek** [comment]
> @pskowronek how about:
> 
>     1. retrieve the default as you do here (the one that appears in Preferences -> Misc -> Run command

Two questions here:
1) But this pref:
obraz
is for running commands (and where you have additional params to launch that command).
In case of terminal we should what? Remove those params and run just the command?

2) Do you mean to use my code to work out macOS' user default shell (like bash or zsh) and use it in pref? But with additional parameters to run the command? We would need to have a list of default params to run a command per known shell (bash, zsh, sh, and whatever else is common out there).

> 
>     2. use that, or the custom shell that the user configures there, in jediterm

But remove parameters? (I'm thinking about `Open Terminal` usage, not run command).

**Comment by ahadas** [comment]
> 1. But this pref:
>    obraz
>    is for running commands (and where you have additional params to launch that command).
>    In case of terminal we should what? Remove those params and run just the command?

Yes, it makes sense to remove/replace those params in my opinion since we no longer just execute commands but rather initialize a terminal from which the user executes commands

> 2. Do you mean to use my code to work out macOS' user default shell (like bash or zsh) and use it in pref?

Yep

> But with additional parameters to run the command? We would need to have a list of default params to run a command per known shell (bash, zsh, sh, and whatever else is common out there).

We already have default params, the `--login`, right? so yeah, to list that and let users override the command and and its parameters if they wish to

> > ```
> > 2. use that, or the custom shell that the user configures there, in jediterm
> > ```
> 
> But remove parameters? (I'm thinking about `Open Terminal` usage, not run command).

I don't think we need to differentiate the terminal view and 'run command' here - is there a reason not to do the same thing for both?

**Comment by pskowronek** [comment]
What about this part?
obraz

I'm looking at the usage of it (`Shell`, `ShellEncodingListener` etc) and encoding autodetection is being done by analyzing the output of the process - doesn't seem to fit JediTerm I guess. Any suggestions?

**Comment by pskowronek** [comment]
FYI - The last PR update was just a rebase to sync with master (and it didn't go smooth :/)

**Comment by pskowronek** [comment]
> What about this part? obraz
> 
> I'm looking at the usage of it (`Shell`, `ShellEncodingListener` etc) and encoding autodetection is being done by analyzing the output of the process - doesn't seem to fit JediTerm I guess. Any suggestions?

So, if we are replacing old run in terminal with JediTerm, I think the whole package `com.mucommander.shell` (Shell, ShellHistoryWriter/Reader/Manager etc) should be removed then. If we want to have autodetect still, then probably things stated in #750 should be used to workout proper settings for LC_ALL/LANG if those env vars are not present.

**Comment by ahadas** [comment]
> What about this part? obraz
> 
> I'm looking at the usage of it (`Shell`, `ShellEncodingListener` etc) and encoding autodetection is being done by analyzing the output of the process - doesn't seem to fit JediTerm I guess. Any suggestions?

I'd drop the auto-detection then

**Comment by pskowronek** [comment]
@ahadas PR updated:
- implemented suggested approach for using shell from prefs
- includes a fix for #750 
- removed files from `com.mucommander.shell` package and any of their references

**Comment by ahadas** [comment]
yeah, something with the rebase looks wrong, I'll have a look

**Review by ahadas — APPROVED** [review]
@pskowronek I've made some cleanup and minor changes - could you please check that this version is alright?

**Comment by pskowronek** [comment]
> @pskowronek I've made some cleanup and minor changes - could you please check that this version is alright?

@ahadas looks good!

**Pull request merged**
