### PR TITLE
Fix to let Reveal In XYZ work on search and parent folder #591

### PR DESCRIPTION
**Pull request by pskowronek**
Fix addressing bug #591 to Reveal In XYZ work when:
- in search results
- clicked on '..'

Tested on macOS **only**

### CODE REVIEW

**Comment by ahadas** [comment]
@pskowronek thanks for posting this. I'm afraid this practice of formatting the file and then changing it is problematic because it's hard to track the changes. could you split it to two different PRs?

**Review by ahadas — CHANGES_REQUESTED** [review]
@pskowronek thanks for posting this. I'm afraid this practice of formatting the file and then changing it is problematic because it's hard to track the changes. could you split it to two different PRs?

**Comment by pskowronek** [comment]
> @pskowronek thanks for posting this. I'm afraid this practice of formatting the file and then changing it is problematic because it's hard to track the changes. could you split it to two different PRs?

If I don't reformat then otherwise I get comments to fix indentation :P 

Here is another PR - https://github.com/mucommander/mucommander/pull/629 - it only contains reformatting of 3 classes, you may either compare these two PRs manually, or push PR 629, then I will rebase this one and only changes will be visible.

BTW - https://stackoverflow.com/a/58738939 ? Wouldn't it work if decided to mass reformat the whole project?

**Comment by pskowronek** [comment]
pls hold on, I need to rebase it properly.

**Comment by ahadas** [comment]
> > @pskowronek thanks for posting this. I'm afraid this practice of formatting the file and then changing it is problematic because it's hard to track the changes. could you split it to two different PRs?
> 
> If I don't reformat then otherwise I get comments to fix indentation :P

:)
not sure how to do that with IntelliJ but Eclipse has a shortcut that defaults to cntl+I that indents the selected lines using the formatter - no need to reformat the entire file for this

> BTW - https://stackoverflow.com/a/58738939 ? Wouldn't it work if decided to mass reformat the whole project? At least fix indentation (tabs->spaces) and CRLF->LF?

could be, I didn't check that

**Comment by pskowronek** [comment]
> :) not sure how to do that with IntelliJ but Eclipse has a shortcut that defaults to cntl+I that indents the selected lines using the formatter - no need to reformat the entire file for this

you know, there's that urge to fix all lines in the file ;)

**Comment by pskowronek** [comment]
Closing this PR, please use https://github.com/mucommander/mucommander/pull/631 instead.

**Pull request closed without merging**
